- name: Restart Chrony
  service:
    name: chrony
    state: restarted
  enabled: yes
  become: yes
  become_user: root

- name: Restart Chronyd
  service:
    name: chronyd
    state: restarted
  enabled: yes
  become: yes
  become_user: root
