---
- name: Uninstall NTP
  yum:
    name: ntp
    state: absent
  become: yes
  become_user: root

- name: Install Chrony
  yum:
    name: chrony
    state: present
  become: yes
  become_user: root

- lineinfile:
    path: /etc/chrony/chrony.conf
    line: 'server 169.254.169.123 prefer iburst'
  become: yes
  become_user: root
  notify:
    - Restart Chronyd
